<?php

namespace ContainerMSyikNh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2hQfeDIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2hQfeDI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2hQfeDI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livraison' => ['privates', '.errored..service_locator.2hQfeDI.App\\Entity\\Livraison', NULL, 'Cannot autowire service ".service_locator.2hQfeDI": it references class "App\\Entity\\Livraison" but no such service exists.'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'livraison' => 'App\\Entity\\Livraison',
            'paginator' => '?',
        ]);
    }
}
