<?php

namespace ContainerMSyikNh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WFSzF5RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WFSzF5R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WFSzF5R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livraison' => ['privates', '.errored..service_locator.WFSzF5R.App\\Entity\\Livraison', NULL, 'Cannot autowire service ".service_locator.WFSzF5R": it references class "App\\Entity\\Livraison" but no such service exists.'],
            'livraisonRepository' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
        ], [
            'livraison' => 'App\\Entity\\Livraison',
            'livraisonRepository' => 'App\\Repository\\LivraisonRepository',
        ]);
    }
}
