<?php

namespace ContainerMSyikNh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__0Al5HYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..0Al5HY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..0Al5HY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pointderelaisRepository' => ['privates', 'App\\Repository\\PointderelaisRepository', 'getPointderelaisRepositoryService', true],
        ], [
            'pointderelaisRepository' => 'App\\Repository\\PointderelaisRepository',
        ]);
    }
}
