<?php

namespace ContainerMSyikNh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivraison2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WFSzF5R.App\Entity\Livraison' shared service.
     *
     * @return \App\Entity\Livraison
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WFSzF5R": it references class "App\\Entity\\Livraison" but no such service exists.');
    }
}
