<?php

namespace ContainerMSyikNh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointderelaisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YbU7OqK.App\Entity\Pointderelais' shared service.
     *
     * @return \App\Entity\Pointderelais
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YbU7OqK": it references class "App\\Entity\\Pointderelais" but no such service exists.');
    }
}
