<?php

namespace ContainerXJNcPIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KNa1GgHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kNa1GgH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kNa1GgH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'liv' => ['privates', '.errored..service_locator.kNa1GgH.App\\Entity\\Livraison', NULL, 'Cannot autowire service ".service_locator.kNa1GgH": it references class "App\\Entity\\Livraison" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'liv' => 'App\\Entity\\Livraison',
        ]);
    }
}
