<?php

namespace Container6PRqUTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YbU7OqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YbU7OqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YbU7OqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pointderelai' => ['privates', '.errored..service_locator.YbU7OqK.App\\Entity\\Pointderelais', NULL, 'Cannot autowire service ".service_locator.YbU7OqK": it references class "App\\Entity\\Pointderelais" but no such service exists.'],
        ], [
            'pointderelai' => 'App\\Entity\\Pointderelais',
        ]);
    }
}
