<?php

namespace Container6PRqUTD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FI6zHhYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FI6zHhY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FI6zHhY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LivraisonController::LivredLivraison' => ['privates', '.service_locator.kNa1GgH', 'get_ServiceLocator_KNa1GgHService', true],
            'App\\Controller\\LivraisonController::delete' => ['privates', '.service_locator.WFSzF5R', 'get_ServiceLocator_WFSzF5RService', true],
            'App\\Controller\\LivraisonController::edit' => ['privates', '.service_locator.WFSzF5R', 'get_ServiceLocator_WFSzF5RService', true],
            'App\\Controller\\LivraisonController::index' => ['privates', '.service_locator.B52ZpTb', 'get_ServiceLocator_B52ZpTbService', true],
            'App\\Controller\\LivraisonController::new' => ['privates', '.service_locator.fL_aq3o', 'get_ServiceLocator_FLAq3oService', true],
            'App\\Controller\\LivraisonController::show' => ['privates', '.service_locator.2hQfeDI', 'get_ServiceLocator_2hQfeDIService', true],
            'App\\Controller\\PointderelaisController::index' => ['privates', '.service_locator.f4oHV50', 'get_ServiceLocator_F4oHV50Service', true],
            'App\\Controller\\PointderelaisFrontController::delete' => ['privates', '.service_locator.mXMhqCb', 'get_ServiceLocator_MXMhqCbService', true],
            'App\\Controller\\PointderelaisFrontController::edit' => ['privates', '.service_locator.mXMhqCb', 'get_ServiceLocator_MXMhqCbService', true],
            'App\\Controller\\PointderelaisFrontController::index' => ['privates', '.service_locator..0Al5HY', 'get_ServiceLocator__0Al5HYService', true],
            'App\\Controller\\PointderelaisFrontController::new' => ['privates', '.service_locator..0Al5HY', 'get_ServiceLocator__0Al5HYService', true],
            'App\\Controller\\PointderelaisFrontController::show' => ['privates', '.service_locator.YbU7OqK', 'get_ServiceLocator_YbU7OqKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\LivraisonController:LivredLivraison' => ['privates', '.service_locator.kNa1GgH', 'get_ServiceLocator_KNa1GgHService', true],
            'App\\Controller\\LivraisonController:delete' => ['privates', '.service_locator.WFSzF5R', 'get_ServiceLocator_WFSzF5RService', true],
            'App\\Controller\\LivraisonController:edit' => ['privates', '.service_locator.WFSzF5R', 'get_ServiceLocator_WFSzF5RService', true],
            'App\\Controller\\LivraisonController:index' => ['privates', '.service_locator.B52ZpTb', 'get_ServiceLocator_B52ZpTbService', true],
            'App\\Controller\\LivraisonController:new' => ['privates', '.service_locator.fL_aq3o', 'get_ServiceLocator_FLAq3oService', true],
            'App\\Controller\\LivraisonController:show' => ['privates', '.service_locator.2hQfeDI', 'get_ServiceLocator_2hQfeDIService', true],
            'App\\Controller\\PointderelaisController:index' => ['privates', '.service_locator.f4oHV50', 'get_ServiceLocator_F4oHV50Service', true],
            'App\\Controller\\PointderelaisFrontController:delete' => ['privates', '.service_locator.mXMhqCb', 'get_ServiceLocator_MXMhqCbService', true],
            'App\\Controller\\PointderelaisFrontController:edit' => ['privates', '.service_locator.mXMhqCb', 'get_ServiceLocator_MXMhqCbService', true],
            'App\\Controller\\PointderelaisFrontController:index' => ['privates', '.service_locator..0Al5HY', 'get_ServiceLocator__0Al5HYService', true],
            'App\\Controller\\PointderelaisFrontController:new' => ['privates', '.service_locator..0Al5HY', 'get_ServiceLocator__0Al5HYService', true],
            'App\\Controller\\PointderelaisFrontController:show' => ['privates', '.service_locator.YbU7OqK', 'get_ServiceLocator_YbU7OqKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\LivraisonController::LivredLivraison' => '?',
            'App\\Controller\\LivraisonController::delete' => '?',
            'App\\Controller\\LivraisonController::edit' => '?',
            'App\\Controller\\LivraisonController::index' => '?',
            'App\\Controller\\LivraisonController::new' => '?',
            'App\\Controller\\LivraisonController::show' => '?',
            'App\\Controller\\PointderelaisController::index' => '?',
            'App\\Controller\\PointderelaisFrontController::delete' => '?',
            'App\\Controller\\PointderelaisFrontController::edit' => '?',
            'App\\Controller\\PointderelaisFrontController::index' => '?',
            'App\\Controller\\PointderelaisFrontController::new' => '?',
            'App\\Controller\\PointderelaisFrontController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LivraisonController:LivredLivraison' => '?',
            'App\\Controller\\LivraisonController:delete' => '?',
            'App\\Controller\\LivraisonController:edit' => '?',
            'App\\Controller\\LivraisonController:index' => '?',
            'App\\Controller\\LivraisonController:new' => '?',
            'App\\Controller\\LivraisonController:show' => '?',
            'App\\Controller\\PointderelaisController:index' => '?',
            'App\\Controller\\PointderelaisFrontController:delete' => '?',
            'App\\Controller\\PointderelaisFrontController:edit' => '?',
            'App\\Controller\\PointderelaisFrontController:index' => '?',
            'App\\Controller\\PointderelaisFrontController:new' => '?',
            'App\\Controller\\PointderelaisFrontController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
