<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWk3hyWW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWk3hyWW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWk3hyWW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWk3hyWW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWk3hyWW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wk3hyWW',
    'container.build_id' => 'a62a3f19',
    'container.build_time' => 1683241763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWk3hyWW');
